version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:13
    container_name: irada_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: irada_redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
