version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    #env_file:
    #  - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      REDISHOST: redis
      REDISPORT: 6379
      REDIS_PASSWORD:
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
