"""добавил рейтинг в telegram_reviews

Revision ID: 2cb11b9e70b4
Revises: b71ac99543ae
Create Date: 2025-04-22 15:54:10.864143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb11b9e70b4'
down_revision: Union[str, None] = 'b71ac99543ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_reviews', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_reviews', 'rating')
    # ### end Alembic commands ###
