name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and run Docker containers
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for Postgres to be ready
        run: |
          until docker compose exec -T db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run Alembic migrations
        run: |
          docker compose exec -T backend alembic upgrade head

      - name: Check service status
        run: |
          docker ps
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8001 || (echo "App not reachable" && docker compose logs)
