name: Deploy to Server

on:
  push:
    branches:
      - main # Запускать, когда есть изменения в ветке main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: your-server-ip
          username: your-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            git pull origin main
            source venv/bin/activate
            pkill uvicorn || true
            nohup uvicorn main.main:app --host 0.0.0.0 --port 8000 &
